# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6190e303ac7981804e806d719a1aca80765d794da8bea652ccb6c5d5dfb14e8ff9a7be5db98207657686cbc15d07776c5cef0221cc5c1c03661a27323a93dc0
  google_client_id: 244000453265-47v0iss6mk5i53n75434itblcigfqold.apps.googleusercontent.com
  google_client_secret: 0TvBpOeMlmZoxO76k_kIqMfs

test:
  secret_key_base: 4a980adf5a7f9bf0f9a67cd7bb64fcee5c8217c901737cb648d2c02d34fece996c2b2c0eda865215c2b20779930afefc01b197be97f167682b3a5593afd0de61
  google_client_id: 244000453265-47v0iss6mk5i53n75434itblcigfqold.apps.googleusercontent.com
  google_client_secret: 0TvBpOeMlmZoxO76k_kIqMfs

sako:
  secret_key_base: 18945b667a7dc4ed408c518d310854829a72bd5639028230d97259f834bce3e626864ec66196dfbe0380211f7936b5da2ce7a2a1c982182dbe0335874c3d655c
  google_client_id: 244000453265-47v0iss6mk5i53n75434itblcigfqold.apps.googleusercontent.com
  google_client_secret: 0TvBpOeMlmZoxO76k_kIqMfs

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: 244000453265-47v0iss6mk5i53n75434itblcigfqold.apps.googleusercontent.com
  google_client_secret: 0TvBpOeMlmZoxO76k_kIqMfs
